version: '3.8'

services:
  app:
    image: beugre/beugre:latest
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: test
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: test
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
